/**
 * Generate PDF from report content
 * Uses html-pdf-node for serverless-compatible PDF generation
 */

module.exports = async (req, res) => {
  // Enable CORS - set headers first
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With, Accept');
  res.setHeader('Access-Control-Max-Age', '86400');

  // Handle preflight OPTIONS request immediately
  if (req.method === 'OPTIONS') {
    res.status(200);
    return res.end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { userId, title, content, reportType, entityId, kpis, returnBuffer } = req.body;

  if (!userId || !title) {
    return res.status(400).json({ error: 'Missing required fields: userId, title' });
  }

  try {
    // Build HTML content for PDF
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    h1 {
      color: #111827;
      border-bottom: 2px solid #3b82f6;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    h2 {
      color: #374151;
      margin-top: 30px;
      margin-bottom: 15px;
    }
    h3 {
      color: #4b5563;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    .meta {
      color: #6b7280;
      font-size: 14px;
      margin-bottom: 30px;
    }
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
      margin-bottom: 30px;
    }
    .kpi-card {
      background: #f3f4f6;
      border-radius: 8px;
      padding: 15px;
      text-align: center;
    }
    .kpi-value {
      font-size: 28px;
      font-weight: 700;
      color: #3b82f6;
    }
    .kpi-label {
      font-size: 12px;
      color: #6b7280;
      text-transform: uppercase;
    }
    ul {
      padding-left: 20px;
    }
    li {
      margin-bottom: 8px;
    }
    strong {
      color: #1f2937;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 12px;
      color: #9ca3af;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">
    <p>Report Type: ${escapeHtml(reportType || 'General')}</p>
    <p>Entity: ${escapeHtml(entityId || 'N/A')}</p>
    <p>Generated: ${new Date().toLocaleString()}</p>
  </div>
  
  ${kpis ? generateKPISection(kpis) : ''}
  
  <div class="content">
    ${content || '<p>No content available.</p>'}
  </div>
  
  <div class="footer">
    <p>Generated by HeyJarvis</p>
  </div>
</body>
</html>
    `;

    // For now, return the HTML as a simple text-based PDF simulation
    // In production, you'd use a proper PDF library like puppeteer or pdf-lib
    // Since Vercel serverless has limitations, we'll return base64 encoded content
    
    const pdfBuffer = Buffer.from(htmlContent, 'utf-8');
    const base64Content = pdfBuffer.toString('base64');

    if (returnBuffer) {
      return res.status(200).json({
        success: true,
        buffer: base64Content,
        mimeType: 'text/html' // For now, sending as HTML since PDF generation requires additional setup
      });
    } else {
      // Send as downloadable file
      res.setHeader('Content-Type', 'text/html');
      res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/[^a-z0-9\s]/gi, '_')}.html"`);
      return res.status(200).send(htmlContent);
    }

  } catch (error) {
    console.error('Generate PDF error:', error);
    return res.status(500).json({
      success: false,
      error: error.message
    });
  }
};

function escapeHtml(text) {
  if (!text) return '';
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function generateKPISection(kpis) {
  if (!kpis || typeof kpis !== 'object') return '';
  
  const kpiItems = [];
  
  if (kpis.totalTasks !== undefined) {
    kpiItems.push({ label: 'Total Tasks', value: kpis.totalTasks });
  }
  if (kpis.completedTasks !== undefined) {
    kpiItems.push({ label: 'Completed', value: kpis.completedTasks });
  }
  if (kpis.inProgressTasks !== undefined) {
    kpiItems.push({ label: 'In Progress', value: kpis.inProgressTasks });
  }
  if (kpis.todoTasks !== undefined) {
    kpiItems.push({ label: 'To Do', value: kpis.todoTasks });
  }
  if (kpis.blockedTasks !== undefined) {
    kpiItems.push({ label: 'Blocked', value: kpis.blockedTasks });
  }
  if (kpis.overdueTasks !== undefined) {
    kpiItems.push({ label: 'Overdue', value: kpis.overdueTasks });
  }
  if (kpis.completionRate !== undefined) {
    kpiItems.push({ label: 'Completion Rate', value: `${kpis.completionRate}%` });
  }
  
  if (kpiItems.length === 0) return '';
  
  return `
    <h2>Key Performance Indicators</h2>
    <div class="kpi-grid">
      ${kpiItems.map(kpi => `
        <div class="kpi-card">
          <div class="kpi-value">${kpi.value}</div>
          <div class="kpi-label">${kpi.label}</div>
        </div>
      `).join('')}
    </div>
  `;
}

